/* =========================================================
   LAB 10 — APPLICANT SCREENING CRITERIA
   ========================================================= */

/* ---------------------------------------------------------
   CREATE TABLE
   --------------------------------------------------------- */

create table if not exists public.screening_criteria (
    criterion_id bigint generated by default as identity primary key,

    criterion_name text not null,

    description text,

    weight numeric(5,2) not null default 0,

    is_active boolean not null default true,

    created_at timestamptz not null default now(),

    updated_at timestamptz not null default now(),

    constraint screening_criteria_weight_check
        check (weight >= 0 and weight <= 100)
);


/* ---------------------------------------------------------
   ENABLE ROW LEVEL SECURITY
   --------------------------------------------------------- */

alter table public.screening_criteria
enable row level security;


/* ---------------------------------------------------------
   GRANTS
   --------------------------------------------------------- */

grant select, insert, update, delete
on table public.screening_criteria
to authenticated;


/* ---------------------------------------------------------
   REMOVE OLD POLICIES IF THEY EXIST
   --------------------------------------------------------- */

drop policy if exists
"Authenticated users can view screening criteria"
on public.screening_criteria;

drop policy if exists
"Authenticated users can insert screening criteria"
on public.screening_criteria;

drop policy if exists
"Authenticated users can update screening criteria"
on public.screening_criteria;

drop policy if exists
"Authenticated users can delete screening criteria"
on public.screening_criteria;


/* ---------------------------------------------------------
   SELECT POLICY
   --------------------------------------------------------- */

create policy
"Authenticated users can view screening criteria"
on public.screening_criteria
for select
to authenticated
using (true);


/* ---------------------------------------------------------
   INSERT POLICY
   --------------------------------------------------------- */

create policy
"Authenticated users can insert screening criteria"
on public.screening_criteria
for insert
to authenticated
with check (true);


/* ---------------------------------------------------------
   UPDATE POLICY
   --------------------------------------------------------- */

create policy
"Authenticated users can update screening criteria"
on public.screening_criteria
for update
to authenticated
using (true)
with check (true);


/* ---------------------------------------------------------
   DELETE POLICY
   --------------------------------------------------------- */

create policy
"Authenticated users can delete screening criteria"
on public.screening_criteria
for delete
to authenticated
using (true);


/* ---------------------------------------------------------
   SEED LAB 10 CRITERIA
   --------------------------------------------------------- */

insert into public.screening_criteria
    (
        criterion_name,
        description,
        weight,
        is_active
    )
select
    v.criterion_name,
    v.description,
    v.weight,
    true
from (
    values
        (
            'Education',
            'Evaluate the applicant''s educational background and relevance to the position.',
            20.00
        ),
        (
            'Work Experience',
            'Evaluate the applicant''s previous work experience and relevance to the position.',
            25.00
        ),
        (
            'Technical Skills',
            'Evaluate the applicant''s technical and job-related skills.',
            30.00
        ),
        (
            'Certifications',
            'Evaluate relevant professional, technical, or industry certifications.',
            10.00
        ),
        (
            'Resume Quality',
            'Evaluate the completeness, organization, clarity, and relevance of the resume.',
            15.00
        )
) as v(
    criterion_name,
    description,
    weight
)
where not exists (
    select 1
    from public.screening_criteria sc
    where lower(trim(sc.criterion_name)) =
          lower(trim(v.criterion_name))
);


/* ---------------------------------------------------------
   OPTIONAL UPDATED_AT TRIGGER
   --------------------------------------------------------- */

create or replace function public.update_screening_criteria_timestamp()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;


/* Remove existing trigger before recreating */
drop trigger if exists
screening_criteria_updated_at
on public.screening_criteria;


/* Create trigger */
create trigger screening_criteria_updated_at
before update on public.screening_criteria
for each row
execute function public.update_screening_criteria_timestamp();